apiVersion: apps/v1
kind: Deployment
metadata:
  name: hometaskxabi
  labels:
    app: hometaskxabi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hometaskxabi
  template:
    metadata:
      labels:
        app: hometaskxabi
    spec:
      containers:
        - name: hometaskxabi
          image: 299903181087.dkr.ecr.eu-west-3.amazonaws.com/demoapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080