version: "3.8"
services:
  postgres:
    image: postgres:9.5
    network_mode: bridge
    container_name: postgres
    volumes:
      - C:\datos2:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    env_file:
         - 'config.env'
    restart: unless-stopped

# This is my rest api app*****************************************
  demoapp:
    build: .
    image: demoapp:latest
    network_mode: bridge
    container_name: demo
    expose:
      - 8080
    ports:
      - 8081:8080
    env_file:
         - 'config.env'